POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNlcmdpb0BnbWFpbC5jb20iLCJleHAiOjE3MTQ0NTI4MDgsInVzZXJJZCI6Mn0.yQGwWpQNF9ZCRiqIZEq4CEVnD39mTRaIlw9axV8GEFg

{
  "name": "first party",
  "description": "Test event!!!",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}